// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Express = require("express");

var app = Express();

app.get("/", (function (param, res) {
        res.send("hi");
        return /* () */0;
      }));

app.get("/hello", (function (param, res) {
        res.send("hello");
        return /* () */0;
      }));

app.get("/world", (function (param, res) {
        res.send("world");
        return /* () */0;
      }));

app.listen(9000);

console.log("listen on port 9000");

exports.app = app;
/* app Not a pure module */
